.shared_windows_runners:
   tags:
     - shared-windows
     - windows
     - windows-1809

before_script:
  - Set-Variable -Name "time" -Value (date -Format "%H:%m")
  - echo ${time}
  - echo "started by ${GITLAB_USER_NAME}"
  - choco install python --version=3.7.0 -y -f
  - choco install cmake

package:
  script:
    - "python -m pip install Cython"
    - python3 io_scene_wmo/build.py | gzip > packaged.gz

  artifacts:
    paths:
    - packaged.gz