.shared_windows_runners:
   tags:
     - shared-windows
     - windows
     - windows-1809

before_script:
  - choco install python --version=3.7.0 -y -f
  - choco install cmake

package:
  script:
    - "python -m pip install Cython"
    - python3 io_scene_wmo/build.py | gzip > packaged.gz

  artifacts:
    paths:
    - packaged.gz